name: Daily Grocery Expiry Check

# Schedule to run every day at 9 AM UTC (adjust timezone as needed)
on:
  schedule:
    - cron: '0 2 * * *'  # 2 AM UTC daily
  workflow_dispatch:  # Allows manual triggering for testing

jobs:
  send-expiry-notifications:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install pymongo python-dotenv dateparser
        
    - name: send_expiry_requirements.py
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
        SMTP_SERVER: smtp.gmail.com
        SMTP_PORT: 587
      run: python send_expiry_notifications.py